name: CI Pull Request

on:
  pull_request:
    branches:
      - '**'

jobs:
  CI-pull-request:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Install CUPS (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libcups2-dev build-essential python-is-python3 gcc g++ make python3-dev
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y gcc-multilib g++-multilib libc6-dev-i386 linux-libc-dev:i386 libcups2-dev:i386
        sudo ldconfig

    - name: Configurar Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Instalar dependÃªncias
      run: npm install --no-save

    - name: Rebuild
      run: npm run rebuild